[defaultTotemFeatures]
healthUponUse = 1
clearEffectsUponUse = true

[defaultTotemFeatures.fireResistance]
enabled = true
duration = 800

[defaultTotemFeatures.regeneration]
enabled = true
duration = 900
amplifier = 1

[defaultTotemFeatures.absorption]
enabled = true
duration = 100
amplifier = 1
[newTotemFeatures]
canUseTotemFromInventory = false
applyEffectsOnlyWhenNecessary = true
customEffects = [[]]

[newTotemFeatures.waterBreathing]
enabled = true
duration = 800

[newTotemFeatures.destroyBlocks]
whenSuffocating = true
whenFullyFrozen = true

[newTotemFeatures.knockbackMobs]
enabled = true
radius = 3.0
strength = 2.5

[newTotemFeatures.cooldown]
enabled = false
cooldown = 200

[newTotemFeatures.teleportOutOfVoid]
enabled = true
teleportHeightOffset = 64
[charm]
canUseTotemFromCharmSlot = true
displayTotemOnChest = true
[blacklists]
blacklistedDimensions = []
blacklistedStructures = []
